repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    # Require ruby-dev package installed:
    rev: 1.11.2
    hooks:
      - id: forbid-binary
      - id: markdownlint # Configure in .mdlrc
      - id: script-must-have-extension
