language: python
jobs:
  include:
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=lint
install: pip install -U tox-travis coveralls
script: tox
cache: pip
after_success: coveralls
deploy:
  provider: pypi
  skip_cleanup: true
  user: "__token__"
  password:
    secure: NuogxDnVFm2IOAxEiKjpMm8Msnfuu+9Up9pN3cicMzl8f/Vqy0J9egRu0vVxew45qP6Emuf2Lxkp/1iofYZjOx2fk0oIBhNo2aA/C7dQ0jI2OcQ4t7vr1DPYdN1iuQcjfc6/iKbgYwXjRRv4yyq26ZSraqoMSGUdyyGNxrYWl3KIcRMgKxO1wdzwh4ckOkdqJcvBxp4gUeT/b6NOprhMcBtPEjhkyc5kdaidrD5079g3+kPcpdoFQwzQ67d7wVzC7LY0j+FFyXVJO8DvWNtd8hewIpaybWWF6NXp/0RyQb82KItFMtpaLMgs0+ZpDjsEr8dwdSJJrv6RCl3rHcZQiI+sWk2++giaPB3XHpW0w+EZyUfQGUpFwgC3EHtDrEQQaaAkV2oNM9CDK03sGI4bDv62A5Mlj70SKxRMBJ6VJ/mhEIgOLvCatpwIsaJKgIwpsjB8vLm6XeCXBdLCBgJfEkDE2j6mOsLvEmfTxUOqxvigcuqga8/i51Y3K/UBrRdQZG45bvDlbdeHNO/tB6qnVGK44op3nmDs7t1tW/OCngfD7nPYhHvMD2p3uDqZN2iiVmgcw6hIrQ3fWInj5QDWN3X8l9DTDZmJbScf/2kXIyzPNuPKFMUApQuC7vII5bHLsojmSfObUFVF+m7UOTJ3vWG+sfW0NAkaK+tu/OQuIT0=
  on:
    branch: master
  skip_existing: true
